# Generated by Django 4.1 on 2024-04-24 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(default="now")),
                ("title", models.CharField(max_length=30)),
                ("caption", models.TextField()),
                ("image", models.ImageField(upload_to="media")),
                (
                    "is_publish",
                    models.BooleanField(
                        default=False, help_text="it will ad when check"
                    ),
                ),
                (
                    "publiasher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_add",),
                "get_latest_by": "date_add",
            },
        ),
    ]
