# Generated by Django 4.1 on 2024-04-24 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_rename_publiasher_ad_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={},
        ),
    ]
