# Generated by Django 4.1 on 2024-04-24 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_alter_ad_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"get_latest_by": "date_add", "ordering": ("-date_add",)},
        ),
        migrations.AlterField(
            model_name="ad",
            name="date_add",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
